#!/bin/bash

if [ -d ".meteor" ]; then
DIR="${PWD##}"
LOCALDIR=/home/vagrant$DIR/.meteor/local
echo "DIR: $DIR"


echo create mount source
mkdir -p $LOCALDIR

echo replace targets with empty directories
umount .meteor/local -f
rm .meteor/local -rf
mkdir .meteor/local

echo mount sources to targets
mount --bind $LOCALDIR .meteor/local

echo done
else
echo Can only be run from a Meteor app directory
fi
